services:
  postgres:
    image: postgres:16
    container_name: conecta_eletivas_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: conecta_eletivas_bd
      POSTGRES_USER: conecta_eletivas_bd_user
      POSTGRES_PASSWORD: 40Dy7UhIRtnHX2t76DMLq4H8EXDNKsmh

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conecta_eletivas_bd_user -d conecta_eletivas_bd"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: